#name: CI/CD Pipeline
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#      - name: Build and Test
#        run: mvn clean test
#      - name: Generate Allure Report
#        run: mvn allure:report
#      - name: Publish Allure Report
#        uses: actions/upload-artifact@v4  # Updated to v4
#        with:
#          name: allure-report
#          path: target/site/allure-maven-plugin/


name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          wget -N http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          sudo mv -f chromedriver /usr/local/bin/chromedriver
      - name: Build and Test
        run: mvn clean test -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver
      - name: Generate Allure Report
        run: mvn allure:report
      - name: Publish Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: target/site/allure-maven-plugin
          publish_branch: gh-pages
      - name: Debug Test Output
        run: |
          echo "Surefire Reports:"
          cat target/surefire-reports/*.txt || true
          echo "Allure Results Count:"
          ls -l allure-results/ | grep json | wc -l || true