name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Nuclear Cleanup
        run: |
          mvn clean
          rm -rf allure-results target/surefire-reports || true

      - name: Set up Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo ln -s /usr/bin/google-chrome /usr/bin/chrome
          echo "CHROME_VERSION=$(google-chrome --version)" >> $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test with Diagnostics
        run: |
          mvn test -B -e -X \
            -Dchrome.options.args="--headless --disable-gpu --no-sandbox --disable-dev-shm-usage --user-data-dir=/tmp/chrome_profile"
          echo "=== TestNG XML Verification ==="
          cat testng.xml
          echo "=== Surefire Reports ==="
          ls -la target/surefire-reports/

      - name: Generate Clean Allure Report
        run: |
          mvn allure:report -Dallure.results.directory=target/fresh-results

      - name: Publish Allure Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: target/site/allure-maven-plugin
          publish_branch: gh-pages
          force_orphan: true