name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 1) get your code
      - uses: actions/checkout@v3

      # 2) set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3) run your tests and generate the Allure report
      - name: Build, Test & Generate Allure
        run: |
          mvn clean test
          mvn allure:report

      # 4) upload the folder as a GitHub Pages artifact
      - name: Upload Allure report for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: target/site/allure-maven-plugin

  deploy-pages:
    needs: build-and-publish
    runs-on: ubuntu-latest
    permissions:
      # required to push to gh-pages
      pages: write
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-pages-artifact@v1

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

#name: CI/CD Pipeline
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#      - name: Cache Maven dependencies
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: ${{ runner.os }}-maven-
#      - name: Install Chrome and ChromeDriver
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y google-chrome-stable
#          CHROME_VERSION=$(google-chrome-stable --version --no-sandbox | grep -oP '\d+\.\d+\.\d+' || echo "136.0.7103")
#          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION || echo "136.0.7103.59")
#          wget -q -O chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip || { echo "Failed to download ChromeDriver"; exit 1; }
#          unzip chromedriver.zip || { echo "Failed to unzip ChromeDriver"; exit 1; }
#          chmod +x chromedriver
#          sudo mv chromedriver /usr/local/bin/
#        shell: /usr/bin/bash {0}  # Remove -e to prevent premature exit
#      - name: Debug Chrome and ChromeDriver
#        run: |
#          google-chrome-stable --version --no-sandbox || echo "Chrome version check failed"
#          chromedriver --version || echo "ChromeDriver not found"
#      - name: Build and Test
#        run: mvn clean test -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver
#      - name: Generate Allure Report
#        run: mvn allure:report
#      - name: Publish Allure Report
#        uses: actions/upload-artifact@v4
#        with:
#          name: allure-report
#          path: target/site/allure-maven-plugin/
#      - name: Deploy to GitHub Pages
#        if: always()
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GH_PAT }}
#          publish_dir: target/site/allure-maven-plugin
#          publish_branch: gh-pages