name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo ln -s /usr/bin/google-chrome /usr/bin/chrome
          echo "CHROME_VERSION=$(google-chrome --version)" >> $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and Test
        run: |
          mvn clean test -Dchrome.options.args="--headless --disable-gpu --no-sandbox --disable-dev-shm-usage --user-data-dir=/tmp/chrome_profile"

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Publish Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/