name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clean workspace
        run: |
          mvn clean
          rm -rf allure-results target/surefire-reports || true

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # Critical fix for JDK compatibility

      - name: Build and Test with diagnostics
        run: |
          mvn test -B -e -X
          echo "=== TestNG XML Verification ==="
          cat testng.xml
          echo "=== Surefire Reports ==="
          ls -la target/surefire-reports/

      - name: Force Allure Report Clean Generation
        run: |
          mvn allure:report -Dallure.results.directory=target/allure-results

      - name: Publish Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/