name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Nuclear Cleanup
        run: |
          mvn clean
          rm -rf allure-results target/surefire-reports || true

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # Critical fix for test execution

      - name: Build and Test with Diagnostics
        run: |
          mvn test -B -e -X
          echo "=== TestNG XML Verification ==="
          cat testng.xml
          echo "=== Actual Tests Executed ==="
          ls -la target/surefire-reports/

      - name: Generate Clean Allure Report
        run: |
          mvn allure:report -Dallure.results.directory=target/allure-results

      - name: Publish Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: target/site/allure-maven-plugin
          publish_branch: gh-pages